GET http://103.175.218.111:3000/health

###

POST http://103.175.218.111:3000/auth/register
Content-Type: application/json

{
    "email": "",
    "password": "",
    "username": ""
}

###

POST http://103.175.218.111:3000/auth/login
Content-Type: application/json

{
    "identifier": "",
    "password": ""
}
