GET http://localhost:3000/

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "dika@nekopay.id",
    "password": "dika1234",
    "username": "Dika"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identifier": "dika@nekopay.id",
    "password": "dika1234"
}
